<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CastleDefense.Engine\CastleDefense.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\CastleDefense.Engine\Data\master_gadgets.csv" Link="Data\master_gadgets.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\CastleDefense.Engine\Data\master_roster.csv" Link="Data\master_roster.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
